//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocamerSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Option
    {
        public int codeReservation { get; set; }
        public int codeOption { get; set; }
        public int qteDemande { get; set; }
        public int dureeOption { get; set; }
    
        public virtual Option1 Option { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
