//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocamerSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Option1()
        {
            this.Detail_Option = new HashSet<Detail_Option>();
        }
    
        public int codeOption { get; set; }
        public string libelleOption { get; set; }
        public int qteDispo { get; set; }
        public double prixOption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Option> Detail_Option { get; set; }
    }
}
